package com.travel.common.enums;

/**
 * @Description 用户类型枚举类
 * @author Zhiping Sun <szp_9830@163.com>
 * @date 2017年11月27日 下午10:19:13
 */
public enum ResultTypeEnum {

	// 公共错误码 0开头
	FAIL(0, "fail", "失败"),
	SUCCESS(1, "success", "成功"),
	INPUT_PARAM_INVALID(2, "COMMON_INPUT_PARAM_INVALID", "入参无效"),

	// 分销商&供应商错误码 100开头

	// 产品错误码 200开头
	RESERVE_QUOTA_EXISTS(201,"RESERVE_QUOTA_EXISTS","请不要重复设置预留配额"),
	RESERVE_QUOTA_OVERDRAFT(202,"RESERVE_QUOTA_OVERDRAFT","预留配额已超过可售配额"),
	BATCH_SET_PRICE_DATE_ERROR(203,"BATCH_SET_PRICE_DATE_ERROR","日期格式错误"),

	// 订单错误码 300开头
	QUERY_ORDER_LIST_FAIL(300, "QUERY_ORDER_LIST_FAIL", "查询订单详情失败"),
	QUERY_ORDER_DETAIL_FAIL(301, "QUERY_ORDER_DETAIL_FAIL", "查询订单详情失败"),
	QUERY_ORDER_PRODUCT_FAIL(302, "QUERY_ORDER_PRODUCT_FAIL", "查询订单产品列表失败"),
	QUERY_ORDER_RESTRICT_FAIL(303, "QUERY_ORDER_RESTRICT_FAIL", "查询订单条款列表失败"),
	QUERY_ORDER_DAY_PRICE_FAIL(304, "QUERY_ORDER_DAY_PRICE_FAIL", "查询订单每日价格列表失败"),
	CREATE_ORDER_FAIL(305, "CREATE_ORDER_FAIL", "新建订单失败"),
	AGENT_NOT_EXISTS_OR_INVALID(306, "AGENT_NOT_EXISTS_OR_INVALID", "客户不存在或无效"),
	AGENT_CHANNEL_NOT_ENABLE(307, "AGENT_CHANNEL_NOT_ENABLE", "客户未开通该渠道"),
	AGENT_LACK_OF_CREDIT_LINE(308, "AGENT_LACK_OF_CREDIT_LINE", "客户信用额度不足"),
	SUPPLIER_NOT_EXISTS_OR_INVALID(309, "SUPPLIER_NOT_EXISTS_OR_INVALID", "供应商不存在或无效"),
	SUPPLIER_NOT_SUPPLY_THIS_HOTEL(310, "SUPPLIER_NOT_SUPPLY_THIS_HOTEL", "供应商未供应该酒店"),
	ORDER_SALE_PRICE_MUST_GT_ZERO(311, "ORDER_SALE_PRICE_MUST_GT_ZERO", "订单总售价必须大于0"),
	ORDER_PRODUCTS_IS_EMPTY(312, "ORDER_PRODUCTS_IS_EMPTY", "订单产品信息为空"),
	ORDER_PRODUCTS_NOT_BELONG_A_SAME_HOTEL(313, "ORDER_PRODUCTS_NOT_BELONG_A_SAME_HOTEL", "订单产品信息不属于同一个酒店"),
	ORDER_DAY_PRICE_IS_EMPTY(314, "ORDER_DAY_PRICE_IS_EMPTY", "订单每日价格信息为空"),
	ORDER_HOTEL_NOT_EXISTS_OR_INVALID(315, "ORDER_HOTEL_NOT_EXISTS_OR_INVALID", "酒店信息不存在或无效"),
	ORDER_ROOM_NOT_EXISTS_OR_INVALID(316, "ORDER_ROOM_NOT_EXISTS_OR_INVALID", "房型信息不存在或无效"),
	ORDER_PRICEPLAN_NOT_EXISTS_OR_INVALID(317, "ORDER_PRICEPLAN_NOT_EXISTS_OR_INVALID", "价格计划信息不存在或无效"),
	DISSATISFY_OCCUPANCYCLAUSE(318, "DISSATISFY_OCCUPANCYCLAUSE", "不满足入住条款"),
	DISSATISFY_BOOKINGCLAUSE(319, "DISSATISFY_BOOKINGCLAUSE", "不满足提前预订条款"),
	DISSATISFY_BOOKROOMSCLAUSE(320, "DISSATISFY_BOOKROOMSCLAUSE", "不满足预订间数条款"),
	DISSATISFY_CANCELCLAUSE(321, "DISSATISFY_CANCELCLAUSE", "不满足取消条款"),
	QUOTA_IS_EMPTY(322, "QUOTA_IS_EMPTY", "房态配额为空"),
	QUOTA_SALE_DATE_INVALID(323, "QUOTA_SALE_DATE_INVALID", "房态配额售卖日期不正确"),
	QUOTA_NOT_ENOUGH(324, "QUOTA_NOT_ENOUGH", "配额不足"),
	ORDER_DEDUCT_CREDIT_LINE_FAIL(325, "ORDER_DEDUCT_CREDIT_LINE_FAIL", "订单挂账失败"),
	PRICE_IS_EMPTY(326, "PRICE_IS_EMPTY", "底价为空"),
	PRICE_DATE_INVALID(327, "PRICE_DATE_INVALID", "售价售卖日期不正确"),
	CHANNEL_PRICE_INVALID(328, "CHANNEL_PRICE_INVALID", "渠道售价无效"),
	ADDITIONAL_NOT_EXISTS(329, "ADDITIONAL_NOT_EXISTS", "附加费信息不存在"),
	ADDITIONAL_DAY_SALE_DATE_INVALID(330, "ADDITIONAL_DAY_SALE_DATE_INVALID", "附加费每日明细的售卖日期不在产品入离店之间"),
	ADDITIONAL_DAY_CURRENCY_INVALID(331, "ADDITIONAL_DAY_CURRENCY_INVALID", "附加费每日明细的售卖币种和库存不一致"),
	ADDITIONAL_DAY_PRICE_INVALID(332, "ADDITIONAL_DAY_PRICE_INVALID", "附加费每日明细的售卖价格和库存不一致"),
	ORDER_CURRENCY_INVALID(333, "ORDER_CURRENCY_INVALID", "传入的订单总价币种不正确"),
	ORDER_SUM_PRICE_INVALID(334, "ORDER_SUM_PRICE_INVALID", "传入的订单总价不正确"),
	PRODUCT_BASE_CURRENCY_IS_DIFFERENT(335, "PRODUCT_BASE_CURRENCY_IS_DIFFERENT", "多个产品的底价币种不一致"),
	PRODUCT_SALE_B_CURRENCY_IS_DIFFERENT(336, "PRODUCT_SALE_B_CURRENCY_IS_DIFFERENT", "多个产品的渠道售卖币种不一致"),
	PRODUCT_ADDITION_BASE_CURRENCY_IS_DIFFERENT(337, "PRODUCT_ADDITION_BASE_CURRENCY_IS_DIFFERENT", "产品底价币种和附加费底价币种不一致"),
	PRODUCT_ADDITION_SALE_B_CURRENCY_IS_DIFFERENT(338, "PRODUCT_ADDITION_SALE_B_CURRENCY_IS_DIFFERENT", "产品渠道售卖币种和附加费渠道售卖币种不一致"),
	QUERY_ORDER_STATE_FAIL(339, "QUERY_ORDER_STATE_FAIL", "查询订单状态失败"),
	QUERY_ORDER_STATE_PARAMETER_INVALID(340, "QUERY_ORDER_STATE_PARAMETER_INVALID", "查询订单状态参数无效"),
	ORDER_NOT_EXISTS(341, "ORDER_NOT_EXISTS", "订单不存在"),
	ORDER_DUPLICATED(342, "ORDER_DUPLICATED", "存在重复订单"),
	SAVE_ORDER_FAIL(343, "SAVE_ORDER_FAIL", "保存订单失败"),
	SAVE_ORDER_RESTRICT_FAIL(344, "SAVE_ORDER_RESTRICT_FAIL", "保存订单条款失败"),
	SAVE_ORDER_PRODUCT_FAIL(345, "SAVE_ORDER_PRODUCT_FAIL", "保存订单产品失败"),
	SAVE_ORDER_DAY_PRICE_FAIL(346, "SAVE_ORDER_DAY_PRICE_FAIL", "保存订单产品每日价格失败"),
	CHECK_HOTEL_FAIL(347, "CHECK_HOTEL_FAIL", "验证酒店失败"),
	CHECK_ROOM_FAIL(348, "CHECK_ROOM_FAIL", "验证房型失败"),
	CHECK_PRODUCT_FAIL(349, "CHECK_PRODUCT_FAIL", "验证产品失败"),
	CHECK_SUPPLY_FAIL(350, "CHECK_SUPPLY_FAIL", "验证产品供应商失败"),
	CHECK_HOTEL_SUPPLY_RELATION_FAIL(351, "CHECK_HOTEL_SUPPLY_RELATION_FAIL", "验证酒店供应关系失败"),
	CHECK_AGENT_CHANNEL_FAIL(352, "CHECK_AGENT_CHANNEL_FAIL", "验证客户渠道失败"),
	CHECK_CLAUSE_FAIL(353, "CHECK_CLAUSE_FAIL", "验证条款失败"),
	CHECK_SUM_PRICE_FAIL(354, "CHECK_SUM_PRICE_FAIL", "验证总价失败"),
	CHECK_PRODUCT_SUM_PRICE_FAIL(355, "CHECK_PRODUCT_SUM_PRICE_FAIL", "验证产品总价失败"),
	CHECK_ADDITION_SUM_PRICE_FAIL(356, "CHECK_ADDITION_SUM_PRICE_FAIL", "验证附加费总价失败"),
	CHECK_PRODUCT_QUOTA_FAIL(357, "CHECK_PRODUCT_QUOTA_FAIL", "验证产品配额房态失败"),
	DEDUCT_PRODUCT_QUOTA_FAIL(358, "DEDUCT_PRODUCT_QUOTA_FAIL", "扣配额失败"),
	REFUND_PRODUCT_QUOTA_FAIL(359, "REFUND_PRODUCT_QUOTA_FAIL", "退配额失败"),
	RECORD_DEDUCT_REFUND_QUOTA_FAIL(360, "RECORD_DEDUCT_REFUND_QUOTA_FAIL", "记录扣退配额日志失败"),
	ORDER_CODE_IS_EMPTY(361, "ORDER_CODE_IS_EMPTY", "订单号为空"),
	ORDER_DAY_PRICE_NOT_EXISTS(362, "ORDER_DAY_PRICE_NOT_EXISTS", "订单每日价格配额信息不存在"),
	UPDATE_ORDER_FAIL(363, "UPDATE_ORDER_FAIL", "更新订单失败"),
	UPDATE_ORDER_PRODUCT_FAIL(364, "UPDATE_ORDER_PRODUCT_FAIL", "更新订单产品失败"),
	UPDATE_ORDER_DAY_PRICE_FAIL(365, "UPDATE_ORDER_DAY_PRICE_FAIL", "更新订单产品每日价格失败"),
	BASE_CURRENCY_IS_DIFFERENT(366, "BASE_CURRENCY_IS_DIFFERENT", "订单底价币种和产品底价币种不一致"),
	SALE_B_CURRENCY_IS_DIFFERENT(367, "SALE_B_CURRENCY_IS_DIFFERENT", "订单售价币种和产品售价币种不一致"),
	BASE_PRICE_IS_DIFFERENT(368, "BASE_PRICE_IS_DIFFERENT", "订单底价和产品底价不一致"),
	APPLY_CANCEL_ORDER_FAIL(369, "APPLY_CANCEL_ORDER_FAIL", "申请取消失败"),
	GENERATE_ORDER_CODE_FAIL(370, "GENERATE_ORDER_CODE_FAIL", "生成订单号失败"),
	PRICE_PLAN_BASE_PRICE_EMPTY(371, "PRICE_PLAN_BASE_PRICE_EMPTY", "产品底价为空"),

	// 试预订错误码
	CHECKIN_CHECKOUT_DATE_INVALID(371, "CHECKIN_CHECKOUT_DATE_INVALID", "非法入离店日期"),
	CHANNEL_CODE_INVALID(372, "CHANNEL_CODE_INVALID", "非法渠道"),
	SALE_CURRENCY_INVALID(373, "SALE_CURRENCY_INVALID", "非法售卖币种"),
	PRICE_PLAN_NOT_EXISTS(374, "PRICE_PLAN_NOT_EXISTS", "产品不存在"),
	QUERY_PRICE_PLAN_FAIL(375, "QUERY_PRICE_PLAN_FAIL", "查询产品失败"),
	ROOM_NOT_EXISTS(376, "ROOM_NOT_EXISTS", "房型不存在"),
	QUERY_ROOM_FAIL(377, "QUERY_ROOM_FAIL", "查询房型失败"),
	HOTEL_NOT_EXISTS(378, "HOTEL_NOT_EXISTS", "酒店不存在"),
	QUERY_HOTEL_FAIL(379, "QUERY_HOTEL_FAIL", "查询酒店失败"),
	PRODUCT_NOT_ONSALE(390, "PRODUCT_NOT_ONSALE", "产品未上架"),
	QUERY_SALE_STATE_FAIL(391, "QUERY_SALE_STATE_FAIL", "查询产品上架状态失败"),
	QUERY_AGENT_FAIL(392, "QUERY_AGENT_FAIL", "查询客户信息失败"),
	QUERY_PRODUCT_DETAIL_FAIL(393, "QUERY_PRODUCT_DETAIL_FAIL", "查询产品售卖详情失败"),
	PRODUCT_DETAIL_NOT_EXISTS(394, "PRODUCT_DETAIL_NOT_EXISTS", "产品售卖详情不存在"),
	PAY_METHOD_ERROR(395, "PAY_METHOD_ERROR", "产品支付方式错误"),
	BASE_CURRENCY_INVALID(396, "BASE_CURRENCY_INVALID", "非法底价币种"),
	SALE_PRICE_IS_EMPTY(397, "SALE_PRICE_IS_EMPTY", "售价为空"),

	// 财务&报表错误码  400开头
	CHECK_OUT_LIST_EMPTY(401, "CHECK_OUT_LIST_EMPTY", "请选择要标记的数据"),

	;


	public int key;

	public String code;

	public String desc;

	private ResultTypeEnum(int key, String code, String desc) {
		this.key = key;
		this.code = code;
		this.desc = desc;
	}

	public static ResultTypeEnum getEnumByKey(int key) {
		for (ResultTypeEnum ut : ResultTypeEnum.values()) {
			if (ut.key == key) {
				return ut;
			}
		}
		return null;
	}

	public static String getCodeByKey(int key) {
		String code = "";
		for (ResultTypeEnum ut : ResultTypeEnum.values()) {
			if (ut.key == key) {
				code = ut.code;
				break;
			}
		}
		return code;
	}

	public static String getDescByKey(int key) {
		String desc = "";
		for (ResultTypeEnum ut : ResultTypeEnum.values()) {
			if (ut.key == key) {
				desc = ut.desc;
				break;
			}
		}
		return desc;
	}
}
